name = "cardboard"
pages_build_output_dir = "public"
compatibility_date = "2024-09-26"

[[env.production.d1_databases]]
database_id = "ecd69ccc-36a5-439f-9145-bb005dc5174c"
binding = "PRODUCTION_DB"
database_name = "PRODUCTION_DB"
